"""Create initial schema

Revision ID: 0555b2b53ac9
Revises: 
Create Date: 2026-09-28 14:25:29.278494
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('household_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Seoul', nullable=False),
    sa.Column('default_servings', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('tools', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('expiry_alert_days', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{3,1,0}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('household_id', name=op.f('pk_household'))
    )
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=100)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('is_pantry_staple', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('pk_ingredient')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_ingredient_canonical_name'))
    )
    op.create_index('ix_ingredient_aliases', 'ingredient', ['aliases'], unique=False, postgresql_using='gin')
    op.create_table('video_recipe',
    sa.Column('video_recipe_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('dish_name', sa.String(length=100), nullable=True),
    sa.Column('base_servings', sa.SmallInteger(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unresolved', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('input_kind', sa.String(length=20), server_default='video_url', nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_kind IN ('video_url', 'pasted_text')", name=op.f('ck_video_recipe_input_kind')),
    sa.CheckConstraint("status IN ('pending', 'analyzed', 'failed')", name=op.f('ck_video_recipe_status')),
    sa.PrimaryKeyConstraint('video_recipe_id', name=op.f('pk_video_recipe')),
    sa.UniqueConstraint('video_id', 'prompt_version', name='uq_video_recipe_video_id_prompt_version')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('last_signed_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('kakao', 'google', 'apple', 'device')", name=op.f('ck_app_user_provider')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_app_user_household_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_app_user_provider_provider_user_id')
    )
    op.create_table('command',
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('utterance', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('clarification_question', sa.Text(), nullable=True),
    sa.Column('spoken_response', sa.Text(), nullable=True),
    sa.Column('target_command_id', sa.UUID(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("intent IN ('register', 'consume', 'adjust', 'query', 'correct', 'cancel', 'recommend', 'plan_future', 'unknown')", name=op.f('ck_command_intent')),
    sa.CheckConstraint("status IN ('pending', 'clarifying', 'applied', 'rejected', 'failed', 'superseded', 'reverted')", name=op.f('ck_command_status')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_command_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_command_id'], ['command.command_id'], name=op.f('fk_command_target_command_id')),
    sa.PrimaryKeyConstraint('command_id', name=op.f('pk_command'))
    )
    op.create_index('ix_command_household_id_created_at', 'command', ['household_id', 'created_at'], unique=False)
    op.create_index('ix_command_target_command_id', 'command', ['target_command_id'], unique=False)
    op.create_table('household_ingredient_preference',
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('avoided', 'allergy', 'pantry_staple')", name=op.f('ck_household_ingredient_preference_kind')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_household_ingredient_preference_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name=op.f('fk_household_ingredient_preference_ingredient_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('household_id', 'ingredient_id', 'kind', name=op.f('pk_household_ingredient_preference'))
    )
    op.create_table('ingredient_batch',
    sa.Column('batch_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('qualitative_amount', sa.String(length=20), nullable=True),
    sa.Column('quantity_certainty', sa.String(length=20), server_default='exact', nullable=False),
    sa.Column('storage_location', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('split_from_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quantity_certainty IN ('exact', 'estimated', 'qualitative', 'unknown')", name=op.f('ck_ingredient_batch_quantity_certainty')),
    sa.CheckConstraint("storage_location IN ('fridge', 'freezer', 'pantry', 'unknown')", name=op.f('ck_ingredient_batch_storage_location')),
    sa.CheckConstraint('quantity IS NOT NULL OR qualitative_amount IS NOT NULL', name=op.f('ck_ingredient_batch_ck_ingredient_batch_amount_present')),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name=op.f('ck_ingredient_batch_ck_ingredient_batch_quantity_non_negative')),
    sa.CheckConstraint('quantity IS NULL OR unit IS NOT NULL', name=op.f('ck_ingredient_batch_ck_ingredient_batch_unit_present')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_ingredient_batch_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name=op.f('fk_ingredient_batch_ingredient_id')),
    sa.ForeignKeyConstraint(['split_from_batch_id'], ['ingredient_batch.batch_id'], name=op.f('fk_ingredient_batch_split_from_batch_id')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_ingredient_batch'))
    )
    op.create_index('ix_ingredient_batch_household_active', 'ingredient_batch', ['household_id', 'deleted_at'], unique=False)
    op.create_index('ix_ingredient_batch_household_ingredient', 'ingredient_batch', ['household_id', 'ingredient_id'], unique=False)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('base_servings', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('estimated_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('video_recipe_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'llm', 'video')", name=op.f('ck_recipe_source')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_recipe_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_recipe_id'], ['video_recipe.video_recipe_id'], name=op.f('fk_recipe_video_recipe_id')),
    sa.PrimaryKeyConstraint('recipe_id', name=op.f('pk_recipe'))
    )
    op.create_index('ix_recipe_household_id_source', 'recipe', ['household_id', 'source'], unique=False)
    op.create_table('batch_date',
    sa.Column('batch_date_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('raw_text', sa.String(length=200), nullable=True),
    sa.Column('source_image_uri', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('use_by', 'sell_by', 'best_before', 'manufactured', 'packed', 'check_reminder')", name=op.f('ck_batch_date_kind')),
    sa.CheckConstraint("source IN ('voice', 'label_photo', 'manual', 'unknown')", name=op.f('ck_batch_date_source')),
    sa.ForeignKeyConstraint(['batch_id'], ['ingredient_batch.batch_id'], name=op.f('fk_batch_date_batch_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_date_id', name=op.f('pk_batch_date')),
    sa.UniqueConstraint('batch_id', 'kind', name='uq_batch_date_batch_id_kind')
    )
    op.create_index('ix_batch_date_kind_date_value', 'batch_date', ['kind', 'date_value'], unique=False)
    op.create_table('batch_state_event',
    sa.Column('state_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_location', sa.String(length=20), nullable=True),
    sa.Column('to_location', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('purchased', 'stocked_in', 'opened', 'portioned', 'frozen', 'thawed', 'moved')", name=op.f('ck_batch_state_event_kind')),
    sa.ForeignKeyConstraint(['batch_id'], ['ingredient_batch.batch_id'], name=op.f('fk_batch_state_event_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['command_id'], ['command.command_id'], name=op.f('fk_batch_state_event_command_id')),
    sa.PrimaryKeyConstraint('state_event_id', name=op.f('pk_batch_state_event'))
    )
    op.create_index('ix_batch_state_event_batch_id_occurred_at', 'batch_state_event', ['batch_id', 'occurred_at'], unique=False)
    op.create_table('change_event',
    sa.Column('change_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quantity_before', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quantity_after', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('certainty', sa.String(length=20), server_default='exact', nullable=False),
    sa.Column('reverses_event_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('stock_in', 'consume', 'adjust', 'discard', 'move', 'split', 'revert')", name=op.f('ck_change_event_action')),
    sa.CheckConstraint("certainty IN ('exact', 'estimated', 'qualitative', 'unknown')", name=op.f('ck_change_event_certainty')),
    sa.ForeignKeyConstraint(['batch_id'], ['ingredient_batch.batch_id'], name=op.f('fk_change_event_batch_id')),
    sa.ForeignKeyConstraint(['command_id'], ['command.command_id'], name=op.f('fk_change_event_command_id')),
    sa.ForeignKeyConstraint(['reverses_event_id'], ['change_event.change_event_id'], name=op.f('fk_change_event_reverses_event_id')),
    sa.PrimaryKeyConstraint('change_event_id', name=op.f('pk_change_event'))
    )
    op.create_index('ix_change_event_batch_id_created_at', 'change_event', ['batch_id', 'created_at'], unique=False)
    op.create_index('ix_change_event_command_id', 'change_event', ['command_id'], unique=False)
    op.create_table('menu_suggestion',
    sa.Column('suggestion_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_order', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('servings', sa.SmallInteger(), nullable=False),
    sa.Column('priority_ingredient_ids', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumption_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability IN ('ready', 'needs_check', 'needs_purchase')", name=op.f('ck_menu_suggestion_availability')),
    sa.ForeignKeyConstraint(['command_id'], ['command.command_id'], name=op.f('fk_menu_suggestion_command_id')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_menu_suggestion_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name=op.f('fk_menu_suggestion_recipe_id')),
    sa.PrimaryKeyConstraint('suggestion_id', name=op.f('pk_menu_suggestion'))
    )
    op.create_index('ix_menu_suggestion_household_id_created_at', 'menu_suggestion', ['household_id', 'created_at'], unique=False)
    op.create_table('recipe_ingredient',
    sa.Column('recipe_ingredient_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_essential', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_amount_unknown', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name=op.f('fk_recipe_ingredient_ingredient_id')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], name=op.f('fk_recipe_ingredient_recipe_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_ingredient_id', name=op.f('pk_recipe_ingredient'))
    )
    op.create_index('ix_recipe_ingredient_recipe_id', 'recipe_ingredient', ['recipe_id'], unique=False)
    op.create_table('shopping_item',
    sa.Column('shopping_item_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('available_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('shortage_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('needs_confirm', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_recipe_id', sa.BigInteger(), nullable=True),
    sa.Column('search_query', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'searched', 'purchased', 'stocked_in', 'dismissed')", name=op.f('ck_shopping_item_status')),
    sa.CheckConstraint('shortage_quantity IS NULL OR shortage_quantity >= 0', name=op.f('ck_shopping_item_ck_shopping_item_shortage_non_negative')),
    sa.ForeignKeyConstraint(['household_id'], ['household.household_id'], name=op.f('fk_shopping_item_household_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], name=op.f('fk_shopping_item_ingredient_id')),
    sa.ForeignKeyConstraint(['source_recipe_id'], ['recipe.recipe_id'], name=op.f('fk_shopping_item_source_recipe_id')),
    sa.PrimaryKeyConstraint('shopping_item_id', name=op.f('pk_shopping_item'))
    )
    op.create_index('ix_shopping_item_household_id_status', 'shopping_item', ['household_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_item_household_id_status', table_name='shopping_item')
    op.drop_table('shopping_item')
    op.drop_index('ix_recipe_ingredient_recipe_id', table_name='recipe_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_index('ix_menu_suggestion_household_id_created_at', table_name='menu_suggestion')
    op.drop_table('menu_suggestion')
    op.drop_index('ix_change_event_command_id', table_name='change_event')
    op.drop_index('ix_change_event_batch_id_created_at', table_name='change_event')
    op.drop_table('change_event')
    op.drop_index('ix_batch_state_event_batch_id_occurred_at', table_name='batch_state_event')
    op.drop_table('batch_state_event')
    op.drop_index('ix_batch_date_kind_date_value', table_name='batch_date')
    op.drop_table('batch_date')
    op.drop_index('ix_recipe_household_id_source', table_name='recipe')
    op.drop_table('recipe')
    op.drop_index('ix_ingredient_batch_household_ingredient', table_name='ingredient_batch')
    op.drop_index('ix_ingredient_batch_household_active', table_name='ingredient_batch')
    op.drop_table('ingredient_batch')
    op.drop_table('household_ingredient_preference')
    op.drop_index('ix_command_target_command_id', table_name='command')
    op.drop_index('ix_command_household_id_created_at', table_name='command')
    op.drop_table('command')
    op.drop_table('app_user')
    op.drop_table('video_recipe')
    op.drop_index('ix_ingredient_aliases', table_name='ingredient', postgresql_using='gin')
    op.drop_table('ingredient')
    op.drop_table('household')
    # ### end Alembic commands ###
